name: Make reviews requested by users 

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Python script
      run: python user.py
      env:
        CLAUDE_KEY: ${{ secrets.CLAUDE_KEY }}
        MISTRAL_KEY: ${{ secrets.MISTRAL_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        FAL_KEY: ${{ secrets.FAL_KEY }}

    - name: Test commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto. Make Doomgrad HF Review on $(date +"%d %B")"

    - name: Pull latest changes from remote
      run: git pull origin main

    - name: Push changes back to GitHub
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

